name: pokedex
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  async_redux: ^15.0.0
  cupertino_icons: ^1.0.2
  dartx: ^1.1.0
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.1
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^5.0.2
  json_annotation: ^4.1.0
  build_runner: ^2.1.2
  pedantic: ^1.11.0
  intl: ^0.17.0

flutter:
  uses-material-design: true
