import 'package:flutter/material.dart';

const Color white = Colors.white;
const Color black = Colors.black;
const Color red = Colors.red;
const Color orangeAccent = Colors.orangeAccent;
const Color labelGrey = Color(0xFF424242);
const Color kFire = Color(0xfffa6e70);
const Color kGrass = Color(0xff51d0b1);
const Color kWater = Color(0xff79c0fb);
const Color kNormal = Color(0xffaca877);
const Color kFlying = Color(0xff62b9b2);
const Color kBug = Color(0xff92b93b);
const Color kPoison = Color(0xffc976ea);
const Color kGround = Color(0xff96901c);
const Color kElectric = Color(0xffbfab32);
const Color kFighting = Color(0xfffeafac);
const Color kPsychic = Color(0xfff35a93);
const Color kRock = Color(0xff948352);
const Color kIce = Color(0xff6bd1e4);
const Color kGhost = Color(0xff8d58a2);
const Color kDragon = Color(0xffd2c0f8);
const Color kDark = Color(0xff4f4f4f);
const Color kSteel = Color(0xff7c8e8a);
const Color kFairy = Color(0xfffda1c2);
